---
prod:
  templates:
    - basic.j2
  vars:
    - defaults.yaml
    - prod/notifications.yaml
    - prod/tables.yaml
lab:
  templates:
    - basic.j2
  vars:
    - defaults.yaml
    - lab/notifications.yaml
    - lab/tables.yaml